
version: '3.4'

services:
  backend:
    build:
        context: .
        dockerfile: BACKEND/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - backendvolumev1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bien123
      MONGO_INITDB_ROOT_PASSWORD: bien123
    restart: unless-stopped

volumes:
  backendvolumev1:


#version: '3.4'
#services:
#  backend:
#    build:
#        context: .
#        dockerfile: BACKEND/Dockerfile
#    ports:
#        - "5000:80"
#    depends_on:
#        - db
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:27017"]
#        interval: 10s
#        timeout: 5s
#        retries: 5
#  db:
#    image: mongo:latest
#    ports:
#        - "27017:27017"
#    volumes:
#        - backendvolumev1:/data/db
#    environment:
#        MONGO_INITDB_ROOT_USERNAME: bien123
#        MONGO_INITDB_ROOT_PASSWORD: bien123
#volumes:
#    backendvolumev1: